FROM node:16

ENV CI=true

WORKDIR /app

COPY package.json ./

#COPY yarn.lock ./

RUN yarn add @nestjs/cli --verbose

RUN yarn install

COPY ./ ./

RUN chmod 775 pipeline_scripts/eMAGMA.sh
#RUN chmod 775 pipeline_scripts/Genes.R
#RUN chmod 775 pipeline_scripts/pathway_link.R
#RUN chmod 775 pipeline_scripts/plot_qq_manhattan.R
#RUN chmod 775 pipeline_scripts/plots.R

#install R and packages
RUN apt update
RUN apt-get install -y r-base
RUN apt-get install -y -qq r-cran-qqman

#remove windows line endings
RUN apt-get install dos2unix
RUN dos2unix pipeline_scripts/eMAGMA.sh
#RUN dos2unix pipeline_scripts/Genes.R
#RUN dos2unix pipeline_scripts/pathway_link.R
#RUN dos2unix pipeline_scripts/plot_qq_manhattan.R
#RUN dos2unix pipeline_scripts/plots.R

#RUN yarn run build
CMD [ "yarn", "run", "start:dev" ]
